<?php

echo '


<!-- //MAPA -->

<!-- //MAPA -->


<footer>


    <!-- //Contacto -->

<div class="col-12">
    <div class="row">
        <section class="my-5">
            <div class="row">
                <div class="col-md-8 mx-auto" style="text-align: center; font-size: 1.2em;">

                    <h2>Ubicación</h2>
                    <br>
                    <br>
                    <div id="map-container-google-2" class="z-depth-1-half map-container wow animate__animated animate__fadeInUp" style="background-color: #fff;">
                        <iframe src="https://maps.google.com/maps?q=Universidad+Tecnológica+Fidel+Velázquez&t=&z=17&ie=UTF8&iwloc=&output=embed" frameborder="0"
                          style="border: 0; width: 100%; height: 350px;" allowfullscreen></iframe>
                    </div>

                </div>
            </div>

        </section>
    </div>


<div class="row">
    <section class="contacto">
        <img src="/img/LOGO_TUVSA_DRAGON.svg" alt="LOGO_TUVSA_B">
        <div class="txtCentrado">
            <div class="p-5 rounded" style="background-color: rgba(0, 0, 0, .5); color: #fff;">
                <h1>Contacto</h1>
                <br>
                <p style="color: #fff;">
                    <br>
                    Teléfonos:
                    <br>
                        52-5525-664253<br>
                        52-5536-509706<br>
                        52-5518-465421<br>
                    </ul>
                    <br>
                    Correo:
                    </br>                   
                    jardin.hr@gmail.com
                </p>
            </div>
        </div>
    </section>
</div>


</div>


<!-- //Contacto -->


</footer>




';



?>