<?php

echo '


<nav class="navbar navbar-expand-lg bg-body-tertiary">
<div class="container-fluid">
  <a class="navbar-brand" href="#">TUVSA</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="index.php">Inicio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="somos/quines_somos.app">Quines somos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="galeria/loque_sea.app">Galeria</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">Login</a>
      </li>
    </ul>
    
  </div>
</div>
</nav>
 <header>

                    <!-- This div is  intentionally blank. It creates the transparent black overlay over the video which you can modify in the CSS -->
                    <div class="overlay"></div>
                  
                    <!-- The HTML5 video element that will create the background video on the header -->
                    <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
                      <source src="VIDEO/TUVSA.mp4" type="video/mp4">
                    </video>
                  
                    <!-- The header content -->
                    <div class="container h-200">
                      <div class="d-flex h-100 text-center align-items-center">
                        <div class="w-50 text-white">
                          <h1 class="display-3">
                            <img src="img/LOGO_TUVSA.jpg"class="animate__animated animate__lightSpeedInRight" class="img-fluid" alt="logoTuvsa" style="width: 500px;">
                          </h1>
                          <br>
                          <!-- <h3 class="lead mb-0">TRANSPORTISTAS UNIDOS DEL VALLE DE MÉXICO CLAVE 10 S.A DE CV.</p> -->
                        </div>
                      </div>
                    </div>
                </header>
                <!-- header -->
                <asset>

                </asset>
                <footer>

                </footer>
            </div>

          </div>




';


?>